name: static-tests

on:
  push:
    branches:
      - master
    tags:
      - '[0-9][0-9][0-9][0-9].[0-9][0-9]-RC[0-9]*'
      - '[0-9][0-9][0-9][0-9].[0-9][0-9]'
      - '[0-9][0-9][0-9][0-9].[0-9][0-9].*'
  pull_request:
    branches:
      - '*'

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup git
      run: |
        # Note: ${{ github.base_ref }} is empty when not in a PR
        if [ -n "${{ github.base_ref }}" ]; then
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} --no-tags
        else
          git config diff.renameLimit 16384
        fi
        git config apply.whitespace nowarn
    - name: Fetch riot/riotbuild Docker image
      run: docker pull riot/riotbuild:latest
    - name: Run static-tests
      run: |
        # Note: ${{ github.base_ref }} is empty when not in a PR
        docker run --rm                             \
          -e CI_BASE_BRANCH=${{ github.base_ref }}  \
          -e GITHUB_RUN_ID=${GITHUB_RUN_ID}         \
          -v $(pwd):/data/riotbuild                 \
          riot/riotbuild:latest                     \
          make static-test
