name: Sync to Codeberg
on:
  push:
    branches:
      - '**'

jobs:
  sync-repo-to-codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Sync repo"
        uses: spyoungtech/mirror-action@v0.7.0
        with:
          REMOTE: "${{ vars.CODEBERG_URL }}"
          GIT_USERNAME: ${{ vars.CODEBERG_USERNAME }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
