name: Sync to Codeberg
on:
  push:
    branches:
      - 'master'
      - '[0-9][0-9][0-9][0-9].[0-9][0-9]-branch'

jobs:
  check-secret:
    runs-on: ubuntu-22.04
    outputs:
      secret-configured: ${{ steps.secret-exists-check.outputs.defined }}
    steps:
      - name: Check if Secret is configured
        id: secret-exists-check
        # check if the secrets are configured before running the tasks
        # see: https://stackoverflow.com/a/70249520
        shell: bash
        run: |
          if [ "${{ secrets.CODEBERG_TOKEN }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  sync-repo-to-codeberg:
    runs-on: ubuntu-latest
    needs: [check-secret]
    if: needs.check-secret.outputs.secret-configured == 'true'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Sync repo"
        uses: spyoungtech/mirror-action@v0.7.0
        with:
          REMOTE: "${{ vars.CODEBERG_URL }}"
          GIT_USERNAME: ${{ vars.CODEBERG_USERNAME }}
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
